Sardinian Keyboard
ubports/keyboard-component pull request #121
Opened 2020-04-15 23:03 UTC by adrmzz

With corpus.txt (but empty database).

2020-04-19 10:56 UTC, adrmzz reviewed
updated keyboards with reorganization of special characters (inspired by the [Catalan update](https://github.com/ubports/keyboard-component/pull/124)) and addition of pronouns (·dd, ·l, ·nche, ·nde, ·mi, ·ti, ·si, ·nos, ·bos)

2020-04-20 19:27 UTC, Flohack74 submitted a review, later dismissed

2020-04-20 19:27 UTC, Flohack74 commented on debian/control
> +	 ubuntu-keyboard-scottish-gaelic (>= ${source:Version}),
Please fix indentation here

2020-11-30 19:42 UTC, UniversalSuperBox requested changes
With the DB populated in this PR, I believe it will actually cause the keyboard to overflow the available space on the system-image on some devices. We may need to merge this keyboard without the corpus database, disabling autocorrect.

The corpus text submitted here has no license information. Please add this information to the `debian/copyright` file so we can ensure license compatibility.

2021-05-03 19:48 UTC, adrmzz commented
I am stuck here. Can anyone lend a hand here? Could we simply re-use [AnySoftKeyboard's corpus](https://github.com/AnySoftKeyboard/LanguagePack/blob/master/languages/sardinian/pack/dictionary/LICENSE_for_words_merged.xml.txt), GPL-licensed?

2021-05-04 15:08 UTC, UniversalSuperBox commented
I'm not a lawyer, but I am pretty sure that AnySoftKeyboard's corpus is unusable here. The keyboard is licensed under a variety of licenses, most restrictive is GNU LGPL-3. If we were to include a GPLv3 text in the keyboard, the entire keyboard would need to be licensed under GPLv3. I don't think we can manage that.

So an empty corpus, or providing the license for the corpus you have provided, would be preferable.

2021-05-06 19:24 UTC, adrmzz commented
Sure, we could go for an empty corpus. But I am not sure that "If we were to include a GPLv3 text in the keyboard, the entire keyboard would need to be licensed under GPLv3." Actually, it appears that [ASK is licensed under an Apache License](https://github.com/AnySoftKeyboard/AnySoftKeyboard), whereas [ASK's Sardinian corpus is under GPL3](https://github.com/AnySoftKeyboard/LanguagePack/blob/master/languages/sardinian/pack/dictionary/LICENSE_for_words_merged.xml.txt), which, in turn, is based in another GPL-d corpus.

2021-05-12 22:55 UTC, UniversalSuperBox commented
I'm not sure how AnySoft figured out how to do that, and as far as I'm concerned it's not my business. Licensing a corpus as GPLv3 in the first place made things difficult (since the GPLv3 is a software license, not a license for text or ideas). But I *do* know that GPL and LGPL are only compatible in one direction: You can include LGPL code in a GPL project. You cannot include GPL code in an LGPL project.

I assume it was the dictionary's creator's original intent to never have the dictionary included in anything but a GPL program. Therefore it is incompatible here. Please clear the keyboard's corpus so we can merge this keyboard.

2021-05-13 12:33 UTC, adrmzz commented
corpus cleared

2021-05-14 18:17 UTC, UniversalSuperBox requested changes
I tested the keyboard on a device and found that it does not function. Please fix these syntax errors and re-test the keyboard on your device, then let me know you're ready for another review.

2021-05-14 18:17 UTC, UniversalSuperBox commented on qml/keys/languages.js
> +    if (languageId == "sc")         return i18n.sc("Sardinian");
This should be `i18n.tr,` not `.sc`. The Sardinian keyboard shows up as a blank spot in the list of keyboards at the moment.

2021-05-14 18:17 UTC, UniversalSuperBox commented on plugins/sc/qml/Keyboard_sc.qml
> +            CharKey { label: "d"; shifted: "D"; extended: ["·dd"]; extendedShifted: ["·DD"] }}
There is an extra closing brace on line 53, which is causing the keyboard to fail to load.

2021-05-14 18:17 UTC, UniversalSuperBox commented on plugins/sc/qml/Keyboard_sc.qml
> +            CharKey { label: "b"; shifted: "B"; extended: ["·bi","·bos"]; extendedShifted: ["·BI","·BOS"] }}
Another double closing brace.

2021-05-14 18:17 UTC, UniversalSuperBox commented on plugins/sc/qml/Keyboard_sc_url.qml
> +            CharKey { label: "b"; shifted: "B"; extended: ["·bi","·bos"]; extendedShifted: ["·BI","·BOS"] }}
Double closing brace

2021-05-14 18:17 UTC, UniversalSuperBox commented on plugins/sc/qml/Keyboard_sc_url_search.qml
> +            CharKey { label: "d"; shifted: "D"; extended: ["·dd"]; extendedShifted: ["·DD"] }}
Double closing brace

2021-05-14 18:17 UTC, UniversalSuperBox commented on plugins/sc/qml/Keyboard_sc_url_search.qml
> +            CharKey { label: "n"; shifted: "N"; extended: ["·nche","·nde","·nos","ny","ñ"]; extendedShifted: ["·NCHE","·NDE","·NOS","NY","Ñ"] }
Double closing brace

2021-05-14 18:17 UTC, UniversalSuperBox commented on plugins/sc/src/src.pro
> +lang_db_sc.files += $$PWD/database_sc.db
It appears that the sc database was not rebuilt after removing the corpus: it is still 43MB. Please recreate an empty database as well.

2021-07-08 18:12 UTC, peat-psuwit commented
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your PR is now migrated to:
https://gitlab.com/ubports/core/lomiri-keyboard/-/merge_requests/121
However, you might not be able to push new code into it, as the branch resides in our repository. In case you need to update it, please open a new MR from your (new) fork. I don't have a better solution at the moment.

Sorry for your inconvenience.

2021-07-08 18:12 UTC, closed without merging