update broken link to crossbuilder as fix for #48
ubports/keyboard-component pull request #54
Opened 2018-12-06 20:12 UTC by Danfro

2018-12-11 21:47 UTC, dobey requested changes
This now contains fixes other than for README.md. It's best to make new branches for new fixes, rather than to do everything under the _master_ branch, so they can be proposed separately.

2018-12-12 07:30 UTC, Danfro commented
Sorry, I was not aware of the fact, that a pr would keep adding all commits to that branch. I will try to fix it. I think gitbook provides a chapter about removing commits or something in the line... 🤓

2018-12-17 21:10 UTC, Danfro commented
So, that should be it, hopefully.
I finally managed to move the second commit to another branch (easy) and got that commit removed from my master branch (tricky). ;-)

2018-12-18 13:58 UTC, dobey approved these changes

2018-12-18 13:59 UTC, merged