Add dvorak layout
ubports/keyboard-component pull request #86
Opened 2019-08-24 15:11 UTC by zoenb

2019-08-25 16:22 UTC, UniversalSuperBox commented
Just coming in from the high-level overview, `en-dv` implies that this is a new locale (like en-US and en-UK). I wonder if we should choose another naming convention for a layout that meets the same language requirements as another, but is a different layout.

@kugiigi, thoughts?

2019-08-25 16:56 UTC, zoenb commented
Any suggestions for what that convention should be? I didn't want to just do dv because that implies a separate locale, which isn't really the case.

2019-08-25 17:03 UTC, UniversalSuperBox commented
Maybe an underscore rather than a dash?

2019-08-25 17:05 UTC, UniversalSuperBox commented
...or @. I wonder if that would mess up the build system.

2019-08-25 17:07 UTC, UniversalSuperBox commented
Yes, @dobey recommended `en_US@layout`. That seems sane.

2019-08-25 21:29 UTC, Fuseteam commented
i tried en@flick directly on the device and it worked fine

2019-08-25 23:58 UTC, zoenb commented
I will change the locale code to en@dv and rebuild the package.

2019-08-26 02:21 UTC, kugiigi commented
I've just read this and learned about Dvorak layout but anyway it seems like this has been resolved 😅

I wonder though if this convention would be the thing forward and perhaps the start of supporting different layout per language like in Android?

2019-08-26 02:50 UTC, zoenb commented
@UniversalSuperBox I've migrated to en@dv. Does anything else need to be updated?

2019-08-26 20:28 UTC, UniversalSuperBox commented
I'm trying to figure out why, but the language plugin still compiles as `libenplugin.so`, causing the keyboard to fail to load it.

2019-08-26 21:03 UTC, UniversalSuperBox requested changes
Aha, found the issue!

2019-08-26 21:03 UTC, UniversalSuperBox commented on plugins/en@dv/src/src.pro
> +TARGET          = $$qtLibraryTarget(enplugin)
Change this to `en@dvplugin` to name the `.so` file correctly.

2019-08-27 13:57 UTC, wildeyedskies commented
Try now

2019-08-27 22:41 UTC, UniversalSuperBox requested changes
I've found two issues:

1. Loading the layout crashes the keyboard
1. The layout is called 'en@dv' rather than 'English (Dvorak)' in the settings

This now crashes when loading the keyboard:

```
WARNING: Did not find a dictionary for "en@dv"  - checking for  "en"
[DatabaseConnector] Unable to create/open database: /usr/share/maliit/plugins/com/ubuntu/lib/en@dv/database_en@dv.db
terminate called after throwing an instance of 'SqliteDatabaseConnector::SqliteDatabaseConnectorException'
  what():  unable to open database file
```

This is an interesting error, it appears it should be falling back to the `en` plugin. There are a couple of options here:

1. Edit the packaging so the dvorak keyboard depends on the normal English keyboard and `en@dv/database_en@dv.db` is a symlink to `../en/database_en.db`.
1. Make sure that fallback code it mentions works correctly

I'd prefer option 2, if possible. Or any other options you see.

Do you have an Ubuntu Touch device that you're using to test these changes, perchance? You can install the keyboard by running `sudo ubports-qa install PR-86` whenever you like. If it complains about being out of space, run `sudo mount / -o remount,rw` followed by `sudo apt clean` followed by `sudo mount -t tmpfs tmpfs /var/cache/apt/archives`, then try again.

2019-08-28 03:32 UTC, wildeyedskies commented
My device got a bit messed up from some on-device prototyping, but I will see if I can get it to run the tests properly. The database not loading seems to be a naming issue. It should be loading the English database.

2019-08-28 13:27 UTC, UniversalSuperBox commented
Yes, if the database was renamed then it would be fine. The problem is, you're using the same database as the English version and it's about 5MB. That doesn't sound like a lot, but it's pretty huge for Ubuntu Touch packages... and it's all wasted space. It'd be better to reuse the same English database rather than shipping a second copy.

2019-08-29 03:16 UTC, zoenb commented
I agree, we should not duplicate the database if possible. I think it makes more sense to have the Dvorak layout in the same package as the regular English layout, rather than a separate package with a dependency.

2019-08-29 13:09 UTC, Fuseteam commented
maybe this is a good opportunity to find a way to separate language and layout

2019-08-29 17:27 UTC, zoenb commented
@Fuseteam I think that's a good idea, but I'm not quite sure how to go about it. Should the layouts still be in separate folders or should it be something like en/en@dv?

2019-08-29 17:38 UTC, tallero commented
> I agree, we should not duplicate the database if possible. I think it makes more sense to have the Dvorak layout in the same package as the regular English layout, rather than a separate package with a dependency.

I tried setting the `database-en@dv.db` as a link, but
- or does the `qinstall` does not install symlinks. 
- or the files are not picked.

Can you check the new changes?

2019-08-31 10:10 UTC, Fuseteam commented
@zoenb i was thinking of a separate folder where the layouts reside while the  databases stay where they are
so that layout and database are from different folders
the sheme 'language@layout' could then be used to read the correct language and layout

2019-09-02 13:30 UTC, zoenb commented
@UniversalSuperBox @Fuseteam Would it be reasonable to change the way the westernlanguage plugin handles finding the database? Currently it just looks for `database_<locale>.db` in the plugin's directory. I'd rather avoid copying the database or using symlinks. I have the following suggestions.

1. Allow for the specification of the database file path possibly via the json file or a separate config file for the plugin, which can then be read by setLanguage in the spellpredictworker.cpp file. This would be the most flexible solution but it would also be the most complex, requiring changes to every plugin
2. When looking up the database drop everything after `@`. This would be far simpler to implement and would be consistent if we have additional custom layouts to add in the future, but it is less flexible.

Do either of these solutions sound good? If so, which one would be better?

2019-09-02 15:43 UTC, Fuseteam commented
@zoenb what makes 1 more flexible than 2?
i think option 2 sounds more reasonable

i'll leave the final call to @UniversalSuperBox tho

2019-09-02 17:48 UTC, UniversalSuperBox commented
Problem with 2 is that the database is loaded from the plugin's folder, the same directory where the QML file is located. Unless we start putting multiple layouts in the same folder (as you mentioned), which could work for now. However it'd mean redoing the plugin loading model a bit. Well, it seems like any change we made would mean redoing it a bit.

How deep have you gone into the maliit/ubuntu-keyboard codebase? I've only made a few patches here and there, I'm by no means an expert. You probably have more knowledge that lets you decide the best course of action.

Very long term, I'd like to be able to install layouts or dictionaries from clicks or another packaging format. Short term, I'd say do what's easiest to satisfy the constraints ("Don't copy the database") and don't sweat the rest, or come back to fix it later. This PR did start as a way to add a dvorak layout, after all.

2019-09-04 05:02 UTC, zoenb commented
I think solution 2 is what I'm going to go with. I'm looking to modify the database loading code which lives in the westernlanguagesupport plugin such that it'll ignore all characters after a `@` when it looks for a database. I *think* this is how it should all work, but I'm very new to C++ and I really know next to nothing about maliit itself.

Currently I'm trying to get the build to run without a database, but its failing at dh_install with files missing.
```
dh_install: ubuntu-keyboard-english-dvorak missing files: usr/share/maliit/plugins/com/ubuntu/lib/en@dv/
dh_install: missing files, aborting
debian/rules:37: recipe for target 'override_dh_install' failed
```

2019-09-04 06:12 UTC, tallero commented
OT: I noticed that many projects using `maalit` use different directory build layouts and format. The reason you did not have a patch like this from me in 2016 was that I could not reuse sailfish's dvorak qml layout here.

If it is useful to know, I also noticed from #90 that `qinstall` skips symlinks.

2019-09-04 18:10 UTC, UniversalSuperBox commented
@zoenb, check `debian/ubuntu-keyboard-english-dvorak.install`. This tells dh_install to install those files. If you don't have a `usr/share/maliit/plugins/com/ubuntu/lib/en@dv/` any more, the .install file can be removed. It probably needs to be changed, at least.

2019-09-04 23:59 UTC, zoenb commented
I still have `usr/share/maliit/plugins/com/ubuntu/lib/en@dv/` for the layout, it just doesn't have the database files anymore.

2019-09-06 16:30 UTC, UniversalSuperBox commented
Awesome, now we're cooking! Your layout uses just 53K on disk.

For the layout, is this what you expected it to look like? Do note that you can add extra keyboards to each row if you need to fit more keys. Q and Z surrounding the spacebar seems a little strange compared to other OSK Dvorak layouts I've seen.

![Dvorak keyboard layout](https://user-images.githubusercontent.com/21966173/64444380-a34fcb00-d099-11e9-9498-f874214f9cf7.png)

Ignore the spacebar saying "En@dv", that was fixed by a reboot.

2019-09-06 20:21 UTC, zoenb commented
I based the layout on Andorid's dvorak keyboard, and it has the Q and Z keys in those positions.

2019-09-07 02:14 UTC, UniversalSuperBox commented
Ah interesting. I have no idea how I missed that when searching for 'Dvorak on-screen keyboard'.

2019-09-07 02:45 UTC, UniversalSuperBox commented
I notice a few keys are different from the English keyboard here. In particular, I note that the "D" key is missing its extensions. It's *extremely* unlikely that these characters would be typed in English, however I'd prefer if the new layout followed the convention set by its base layout. That is, if a key cannot be accessed from another location on this layout, just copy the key from the [default English layout](https://github.com/ubports/keyboard-component/blob/xenial/plugins/en/qml/Keyboard_en.qml). Remember to repeat that change in all of your new layouts too.

If you have a good reason not to follow convention, I'll probably agree with you though. What do you think?

2019-09-07 05:36 UTC, zoenb commented
I'll add the D key accents tomorrow. Is there anything else we need before this is good to merge?

2019-09-09 16:33 UTC, UniversalSuperBox requested changes
Yes. T is also missing its accents from the EN keyboard. I believe all these characters are on the English keyboard so that people who do not have a keyboard for their language can still use Ubuntu Touch, and also because English is the fallback for those.

2019-09-10 12:23 UTC, tallero commented
I am using @zoenb layout from last week and it is awesome.

Just to propose, what do you guys think about adding arrow keys in the long press popup or adding them on a third level? I remember this were feasible when playing with maliit on sailfish. There should be keycodes for them somewhere on mer repositories.

I really became addicted to having arrow keys in android navbar (lineageos specific) and it would be really useful to have them not only in the terminal.

2019-09-10 16:56 UTC, UniversalSuperBox commented
@tallero, please file another request for changes. This will be lost here. :)

2019-09-10 21:55 UTC, Fuseteam commented
sounds like a request for an interaction layer xD

2019-09-11 01:10 UTC, Fuseteam commented
@UniversalSuperBox is T the only one left that's missing its accents?

2019-09-11 14:58 UTC, zoenb commented
Alright, that *should* be all the missing accents from the en keyboard.

2019-09-11 20:58 UTC, UniversalSuperBox approved these changes
Everything seems to be in order here. Nice work, and huge thanks! I'll have to get this into the metapackage so it's installed in Ubuntu Touch by default.

2019-09-11 20:59 UTC, merged

2019-09-11 21:00 UTC, UniversalSuperBox commented
@zoenb, is there any specific way you would like to be credited in our changelog for our next release? Would you prefer your username, or another name...?

2019-09-11 21:04 UTC, zoenb commented
Glad to see it get merged. Just zoenb is fine for the changelog. Thanks for asking!

2019-09-11 21:56 UTC, UniversalSuperBox commented
No problem. zoenb it is! Thank you very much. Have you checked out any other parts of Ubuntu Touch, maybe there's something I could point you in the right direction on.

2019-09-11 23:33 UTC, zoenb commented
I've poked through the code a little bit. Do you have a list of work for centralized anywhere or is it just in the individual project issue trackers?

2019-09-12 01:22 UTC, Fuseteam commented
Congrats!

2019-09-12 01:56 UTC, UniversalSuperBox commented
It depends on what you're looking for. The issue tracker for the system is https://github.com/ubports/ubuntu-touch/issues, but if we know that an issue only affects a single component we may move them to that component's repository. Core apps are moving over to https://gitlab.com/ubports. Overarching projects, like stable system updates, are tracked at https://github.com/orgs/ubports/projects. We'd love to hear from you in any of our chatrooms (#ubports on freenode, @ubports on Telegram, #ubports:matrix.org on the Matrix network) or on the forum at forums.ubports.com, if you'd like.

2019-10-17 16:08 UTC, ziggutas commented
Devices: Nexus 7 (flo), BQ E4.5 ubuntu edition. Both on rc (2019-W42)
English Dvorak keyboard layout works on these two devices. Also the special characters for the D and T on the English layout. Always wondered what those were! Feel more acquainted with my keyboard now :D