add a space autocomplete.
ubports/keyboard-component pull request #91
Opened 2019-08-31 19:15 UTC by Fuseteam

add a space after selecting a word in the word ribbon

2019-09-01 19:54 UTC, UniversalSuperBox requested changes
I'm pretty sure we already do this, see https://github.com/ubports/keyboard-component/issues/71#issuecomment-526948115

2019-09-02 00:33 UTC, UniversalSuperBox requested changes
If autocorrect is turned on, this adds two spaces after every word. Instead, you'll need to find a way to add a space after a word whether autocorrect is on or off.

2019-09-02 01:27 UTC, Fuseteam commented
who uses autocorrect :p

i'll look into it

2019-09-05 14:59 UTC, Fuseteam commented
crud need to find where autocorrect adds the space :>

2019-11-20 19:34 UTC, Fuseteam commented
[this](https://github.com/ubports/keyboard-component/commit/a77392afe62b18ac45d7c21d5b50c3551471a52d) commit might provide a hint

2021-04-10 22:26 UTC, Fuseteam commented
.....oops

2021-04-12 15:24 UTC, Fuseteam commented
welp this is one is more difficult than one might suspect, the tests expect autocorrect to add a space, and the code only takes autocorrect in account when appending a space. so at this point a way must be found to also append a space when autoComplete is enabled

2021-07-08 18:10 UTC, peat-psuwit commented
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your PR is now migrated to:
https://gitlab.com/ubports/core/lomiri-keyboard/-/merge_requests/91
However, you might not be able to push new code into it, as the branch resides in our repository. In case you need to update it, please open a new MR from your (new) fork. I don't have a better solution at the moment.

Sorry for your inconvenience.

2021-07-08 18:10 UTC, closed without merging